# Generated by Django 4.2 on 2023-10-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='$', max_length=5)),
                ('delivery', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('reciever_email', models.EmailField(max_length=50)),
                ('admin_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
